# Generated by Django 4.0.6 on 2022-07-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_NO',
            new_name='ord_id',
        ),
    ]
